# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: node-web-app
#   labels:
#     app: node-web-app
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: node-web-app
#   template:
#     metadata:
#       labels:
#         app: node-web-app
#     spec:
#       containers:
#       - name: node-web-app
#         image: your-registry/node-web-app
#         ports:
#         - containerPort: 3000


apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: {{ .Values.image.repo }}
        ports:
        - containerPort: {{ .Values.port }}
